version: "3.9"
services:
  couchdb:
    image: couchdb:3
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - couchdb_data:/opt/couchdb/data
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8001:8001"
    environment:
      - COUCHDB_URL=http://couchdb:5984/
      - COUCHDB_DB=monshin_sessions
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    depends_on:
      - couchdb
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "5173:80"
volumes:
  couchdb_data:
