version: "3.9"
services:
  couchdb:
    image: couchdb:3
    restart: unless-stopped
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - ./data/couchdb:/opt/couchdb/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:5984/_up || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend/app:/app/app
      - ./data/sqlite:/app/data/sqlite
    ports:
      - "8001:8001"
    environment:
      - COUCHDB_URL=http://couchdb:5984/
      - COUCHDB_DB=monshin_sessions
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
      - MONSHINMATE_DB=/app/data/sqlite/app.sqlite3
    depends_on:
      couchdb:
        condition: service_healthy
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "${FRONTEND_HTTP_PORT:-5173}:80"
